/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.2/userguide/building_java_projects.html
 */

/*plugins {
 *   // Apply the java-library plugin for API and implementation separation.
 *  `java-library`
 *	id 'java'
 *	id 'org .jetbrains.kotlin.jvm"version '1.5.21'
 *}
 */

plugins {
    id"application"
}
apply plugin :"java"
ext {
   javaMainClass ="com.mao.WordFrplugins"
}

application {
    mainClassName = javaMainClass
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation("junit:junit:4.13")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:29.0-jre")
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

sourceSets {
	main.java.srcDirs += 'src/main/kotlin'
}

compilKotlin{
	kotlinOptions.jvmTarget = '1.8'
}
